/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CabineRouteImport } from './routes/cabine'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as RoteirizadorRouteImport } from './routes/roteirizador'
import { Route as SpyRouteImport } from './routes/spy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabineRoute = CabineRouteImport.update({
  id: '/cabine',
  path: '/cabine',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirizadorRoute = RoteirizadorRouteImport.update({
  id: '/roteirizador',
  path: '/roteirizador',
  getParentRoute: () => rootRouteImport,
} as any)
const SpyRoute = SpyRouteImport.update({
  id: '/spy',
  path: '/spy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabine': typeof CabineRoute
  '/entrar': typeof EntrarRoute
  '/estudio': typeof EstudioRoute
  '/faq': typeof FaqRoute
  '/painel': typeof PainelRoute
  '/planos': typeof PlanosRoute
  '/produtos': typeof ProdutosRoute
  '/roteirizador': typeof RoteirizadorRoute
  '/spy': typeof SpyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabine': typeof CabineRoute
  '/entrar': typeof EntrarRoute
  '/estudio': typeof EstudioRoute
  '/faq': typeof FaqRoute
  '/painel': typeof PainelRoute
  '/planos': typeof PlanosRoute
  '/produtos': typeof ProdutosRoute
  '/roteirizador': typeof RoteirizadorRoute
  '/spy': typeof SpyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cabine': typeof CabineRoute
  '/entrar': typeof EntrarRoute
  '/estudio': typeof EstudioRoute
  '/faq': typeof FaqRoute
  '/painel': typeof PainelRoute
  '/planos': typeof PlanosRoute
  '/produtos': typeof ProdutosRoute
  '/roteirizador': typeof RoteirizadorRoute
  '/spy': typeof SpyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cabine'
    | '/entrar'
    | '/estudio'
    | '/faq'
    | '/painel'
    | '/planos'
    | '/produtos'
    | '/roteirizador'
    | '/spy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cabine'
    | '/entrar'
    | '/estudio'
    | '/faq'
    | '/painel'
    | '/planos'
    | '/produtos'
    | '/roteirizador'
    | '/spy'
  id:
    | '__root__'
    | '/'
    | '/cabine'
    | '/entrar'
    | '/estudio'
    | '/faq'
    | '/painel'
    | '/planos'
    | '/produtos'
    | '/roteirizador'
    | '/spy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CabineRoute: typeof CabineRoute
  EntrarRoute: typeof EntrarRoute
  EstudioRoute: typeof EstudioRoute
  FaqRoute: typeof FaqRoute
  PainelRoute: typeof PainelRoute
  PlanosRoute: typeof PlanosRoute
  ProdutosRoute: typeof ProdutosRoute
  RoteirizadorRoute: typeof RoteirizadorRoute
  SpyRoute: typeof SpyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabine': {
      id: '/cabine'
      path: '/cabine'
      fullPath: '/cabine'
      preLoaderRoute: typeof CabineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteirizador': {
      id: '/roteirizador'
      path: '/roteirizador'
      fullPath: '/roteirizador'
      preLoaderRoute: typeof RoteirizadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spy': {
      id: '/spy'
      path: '/spy'
      fullPath: '/spy'
      preLoaderRoute: typeof SpyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CabineRoute: CabineRoute,
  EntrarRoute: EntrarRoute,
  EstudioRoute: EstudioRoute,
  FaqRoute: FaqRoute,
  PainelRoute: PainelRoute,
  PlanosRoute: PlanosRoute,
  ProdutosRoute: ProdutosRoute,
  RoteirizadorRoute: RoteirizadorRoute,
  SpyRoute: SpyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
