/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCabineRouteImport } from './routes/_authenticated/cabine'
import { Route as AuthenticatedCofreRouteImport } from './routes/_authenticated/cofre'
import { Route as AuthenticatedCriadoresRouteImport } from './routes/_authenticated/criadores'
import { Route as AuthenticatedEstudioRouteImport } from './routes/_authenticated/estudio'
import { Route as AuthenticatedGravarRouteImport } from './routes/_authenticated/gravar'
import { Route as AuthenticatedIndiqueRouteImport } from './routes/_authenticated/indique'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedRoteirizadorRouteImport } from './routes/_authenticated/roteirizador'
import { Route as AuthenticatedSpyRouteImport } from './routes/_authenticated/spy'
import { Route as AuthenticatedVideoRouteImport } from './routes/_authenticated/video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCabineRoute = AuthenticatedCabineRouteImport.update({
  id: '/cabine',
  path: '/cabine',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCofreRoute = AuthenticatedCofreRouteImport.update({
  id: '/cofre',
  path: '/cofre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCriadoresRoute = AuthenticatedCriadoresRouteImport.update({
  id: '/criadores',
  path: '/criadores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstudioRoute = AuthenticatedEstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGravarRoute = AuthenticatedGravarRouteImport.update({
  id: '/gravar',
  path: '/gravar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndiqueRoute = AuthenticatedIndiqueRouteImport.update({
  id: '/indique',
  path: '/indique',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoteirizadorRoute =
  AuthenticatedRoteirizadorRouteImport.update({
    id: '/roteirizador',
    path: '/roteirizador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSpyRoute = AuthenticatedSpyRouteImport.update({
  id: '/spy',
  path: '/spy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideoRoute = AuthenticatedVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/faq': typeof FaqRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cabine': typeof AuthenticatedCabineRoute
  '/cofre': typeof AuthenticatedCofreRoute
  '/criadores': typeof AuthenticatedCriadoresRoute
  '/estudio': typeof AuthenticatedEstudioRoute
  '/gravar': typeof AuthenticatedGravarRoute
  '/indique': typeof AuthenticatedIndiqueRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/roteirizador': typeof AuthenticatedRoteirizadorRoute
  '/spy': typeof AuthenticatedSpyRoute
  '/video': typeof AuthenticatedVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/faq': typeof FaqRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cabine': typeof AuthenticatedCabineRoute
  '/cofre': typeof AuthenticatedCofreRoute
  '/criadores': typeof AuthenticatedCriadoresRoute
  '/estudio': typeof AuthenticatedEstudioRoute
  '/gravar': typeof AuthenticatedGravarRoute
  '/indique': typeof AuthenticatedIndiqueRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/roteirizador': typeof AuthenticatedRoteirizadorRoute
  '/spy': typeof AuthenticatedSpyRoute
  '/video': typeof AuthenticatedVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/faq': typeof FaqRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/cabine': typeof AuthenticatedCabineRoute
  '/_authenticated/cofre': typeof AuthenticatedCofreRoute
  '/_authenticated/criadores': typeof AuthenticatedCriadoresRoute
  '/_authenticated/estudio': typeof AuthenticatedEstudioRoute
  '/_authenticated/gravar': typeof AuthenticatedGravarRoute
  '/_authenticated/indique': typeof AuthenticatedIndiqueRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/roteirizador': typeof AuthenticatedRoteirizadorRoute
  '/_authenticated/spy': typeof AuthenticatedSpyRoute
  '/_authenticated/video': typeof AuthenticatedVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/faq'
    | '/planos'
    | '/reset-password'
    | '/cabine'
    | '/cofre'
    | '/criadores'
    | '/estudio'
    | '/gravar'
    | '/indique'
    | '/painel'
    | '/produtos'
    | '/roteirizador'
    | '/spy'
    | '/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/faq'
    | '/planos'
    | '/reset-password'
    | '/cabine'
    | '/cofre'
    | '/criadores'
    | '/estudio'
    | '/gravar'
    | '/indique'
    | '/painel'
    | '/produtos'
    | '/roteirizador'
    | '/spy'
    | '/video'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/entrar'
    | '/faq'
    | '/planos'
    | '/reset-password'
    | '/_authenticated/cabine'
    | '/_authenticated/cofre'
    | '/_authenticated/criadores'
    | '/_authenticated/estudio'
    | '/_authenticated/gravar'
    | '/_authenticated/indique'
    | '/_authenticated/painel'
    | '/_authenticated/produtos'
    | '/_authenticated/roteirizador'
    | '/_authenticated/spy'
    | '/_authenticated/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  FaqRoute: typeof FaqRoute
  PlanosRoute: typeof PlanosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cabine': {
      id: '/_authenticated/cabine'
      path: '/cabine'
      fullPath: '/cabine'
      preLoaderRoute: typeof AuthenticatedCabineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cofre': {
      id: '/_authenticated/cofre'
      path: '/cofre'
      fullPath: '/cofre'
      preLoaderRoute: typeof AuthenticatedCofreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criadores': {
      id: '/_authenticated/criadores'
      path: '/criadores'
      fullPath: '/criadores'
      preLoaderRoute: typeof AuthenticatedCriadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudio': {
      id: '/_authenticated/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof AuthenticatedEstudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gravar': {
      id: '/_authenticated/gravar'
      path: '/gravar'
      fullPath: '/gravar'
      preLoaderRoute: typeof AuthenticatedGravarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indique': {
      id: '/_authenticated/indique'
      path: '/indique'
      fullPath: '/indique'
      preLoaderRoute: typeof AuthenticatedIndiqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roteirizador': {
      id: '/_authenticated/roteirizador'
      path: '/roteirizador'
      fullPath: '/roteirizador'
      preLoaderRoute: typeof AuthenticatedRoteirizadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spy': {
      id: '/_authenticated/spy'
      path: '/spy'
      fullPath: '/spy'
      preLoaderRoute: typeof AuthenticatedSpyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video': {
      id: '/_authenticated/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof AuthenticatedVideoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCabineRoute: typeof AuthenticatedCabineRoute
  AuthenticatedCofreRoute: typeof AuthenticatedCofreRoute
  AuthenticatedCriadoresRoute: typeof AuthenticatedCriadoresRoute
  AuthenticatedEstudioRoute: typeof AuthenticatedEstudioRoute
  AuthenticatedGravarRoute: typeof AuthenticatedGravarRoute
  AuthenticatedIndiqueRoute: typeof AuthenticatedIndiqueRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRoteirizadorRoute: typeof AuthenticatedRoteirizadorRoute
  AuthenticatedSpyRoute: typeof AuthenticatedSpyRoute
  AuthenticatedVideoRoute: typeof AuthenticatedVideoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCabineRoute: AuthenticatedCabineRoute,
  AuthenticatedCofreRoute: AuthenticatedCofreRoute,
  AuthenticatedCriadoresRoute: AuthenticatedCriadoresRoute,
  AuthenticatedEstudioRoute: AuthenticatedEstudioRoute,
  AuthenticatedGravarRoute: AuthenticatedGravarRoute,
  AuthenticatedIndiqueRoute: AuthenticatedIndiqueRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRoteirizadorRoute: AuthenticatedRoteirizadorRoute,
  AuthenticatedSpyRoute: AuthenticatedSpyRoute,
  AuthenticatedVideoRoute: AuthenticatedVideoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EntrarRoute: EntrarRoute,
  FaqRoute: FaqRoute,
  PlanosRoute: PlanosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
